import localFont from "next/font/local"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const aeonik = localFont({
  src: [
    {
      path: "./fonts/AeonikPro-Regular.woff",
      weight: "400",
      style: "normal",
    },
    // si tienes más pesos:
    // { path: "./fonts/AeonikPro-Medium.woff", weight: "500", style: "normal" },
    // { path: "./fonts/AeonikPro-Bold.woff", weight: "700", style: "normal" },
  ],
  variable: "--font-aeonik",
  display: "swap",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aeonik.variable} ${geistSans.variable} ${geistMono.variable}`}>
  {children}
</body>

    </html>
  );
}
